import { STAGE_ORDER } from './status-config';
import type { LifecycleSegment, MockOrder, StageKey } from './types';

function lc(
  currentIdx: number,
  rows: Array<[number, number, number]>,
): LifecycleSegment[] {
  return STAGE_ORDER.map((key: StageKey, i): LifecycleSegment => {
    const [weight, cy, tk] = rows[i];
    return {
      key,
      weight,
      cy,
      tk,
      state: i < currentIdx ? 'done' : i === currentIdx ? 'current' : 'future',
    };
  });
}

export const MOCK_ORDERS: MockOrder[] = [
  {
    order_code: 'ORD-104872',
    order_type: 'PR',
    customer_name: 'Coffman Construction',
    project_name: 'Tinker AFB Apron',
    project_code: 'P-552',
    delivery_addr_short: '1200 SE 59th St, OKC',
    delivery_addr_full: '1200 SE 59th St, Oklahoma City, OK 73129',
    ordered_by_name: 'Mike Rourke',
    ordered_by_phone: '(405) 555-0148',
    preferred_communication: 'Text',
    item_code: '4000P',
    description: '4000 PSI Pump',
    order_qty: 45,
    delivered_qty: 27,
    completion_pct: 60,
    ticket_count: 4,
    total_loads: 6,
    plant_name: 'OKC South',
    plant_code: 'P12',
    zone_name: 'OKC Metro',
    start_time: '07:30',
    est_finish_time: '11:15',
    status_category: 'IN_PROCESS',
    sub_status: null,
    current_stage_label: 'Pouring',
    lifecycle_caption: '▼ Pouring 12 CY · 2 tk',
    lifecycle: lc(3, [
      [8, 0, 0],
      [8, 0, 0],
      [8, 8, 1],
      [12, 12, 2],
      [9, 7, 1],
      [8, 0, 0],
      [8, 0, 0],
      [8, 0, 0],
    ]),
    weather: {
      tempF: 78,
      condition: 'Partly cloudy',
      windMph: 12,
      rhPct: 38,
      evaporationLevel: 'High',
      risk: 'risk',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'voice', at: '05/17 14:22' },
      c24: { status: 'confirmed', channel: 'sms', at: '05/18 14:08' },
    },
    confirmation_label: 'Confirmed',
    is_favourite: true,
    unread_chat: 2,
    note_description: 'Pump on site — call 30 min out',
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'pouring', text: 'Truck T-1184 began pouring', time: '08:42' },
      { marker: 'at_job', text: 'Truck T-1182 arrived on site', time: '08:31' },
      { marker: 'poured', text: 'Truck T-1179 finished pour · 7 CY', time: '08:18' },
      { marker: 'info', text: 'Order ticketed at plant', time: '07:24' },
    ],
  },
  {
    order_code: 'ORD-104915',
    order_type: 'PR',
    customer_name: 'Manhattan Road & Bridge',
    project_name: 'I-44 Widening Phase 3',
    project_code: 'P-481',
    delivery_addr_short: 'Sooner Rd, Edmond OK',
    delivery_addr_full: 'Sooner Rd & E 2nd St, Edmond, OK 73034',
    ordered_by_name: 'Dana Whitfield',
    ordered_by_phone: '(405) 555-0193',
    preferred_communication: 'Text',
    item_code: '3000A',
    description: '3000 PSI',
    order_qty: 80,
    delivered_qty: 0,
    completion_pct: 0,
    ticket_count: 0,
    total_loads: 10,
    plant_name: 'Edmond',
    plant_code: 'P04',
    zone_name: 'North Metro',
    start_time: '06:00',
    est_finish_time: '10:30',
    status_category: 'PRE_POUR',
    sub_status: 1,
    current_stage_label: 'Awaiting release',
    lifecycle_caption: '⏳ Customer will release',
    lifecycle: [],
    weather: {
      tempF: 71,
      condition: 'Overcast',
      windMph: 8,
      rhPct: 55,
      evaporationLevel: 'Normal',
      risk: 'none',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'voice', at: '05/17 11:05' },
      c24: { status: 'pending', channel: null, at: null },
    },
    confirmation_label: '24h pending',
    is_favourite: false,
    unread_chat: 0,
    note_description: 'Customer will call to release',
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'info', text: '48h confirmation — voice', time: '05/17 11:05' },
      { marker: 'info', text: 'Order created by Hardik', time: '05/16 16:20' },
    ],
  },
  {
    order_code: 'ORD-104733',
    order_type: 'PR',
    customer_name: 'City of Norman',
    project_name: 'Lindsey St Bridge Deck',
    project_code: 'P-377',
    delivery_addr_short: 'Lindsey St & Berry Rd, Norman',
    delivery_addr_full: 'Lindsey St & Berry Rd, Norman, OK 73069',
    ordered_by_name: 'Carla Jensen',
    ordered_by_phone: '(405) 555-0277',
    preferred_communication: 'Phone',
    item_code: '4500D',
    description: '4500 Bridge Deck',
    order_qty: 30,
    delivered_qty: 30,
    completion_pct: 100,
    ticket_count: 10,
    total_loads: 10,
    plant_name: 'Norman',
    plant_code: 'P21',
    zone_name: 'South Metro',
    start_time: '05:30',
    est_finish_time: '08:42',
    status_category: 'COMPLETED',
    sub_status: null,
    current_stage_label: 'All loads home',
    lifecycle_caption: '✓ All loads home',
    lifecycle: lc(7, [
      [1, 0, 0],
      [1, 0, 0],
      [1, 0, 0],
      [1, 0, 0],
      [1, 30, 10],
      [1, 0, 0],
      [1, 0, 0],
      [1, 30, 10],
    ]),
    weather: {
      tempF: 68,
      condition: 'Cloudy',
      windMph: 6,
      rhPct: 60,
      evaporationLevel: 'Low',
      risk: 'none',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'voice', at: '05/17 09:00' },
      c24: { status: 'confirmed', channel: 'manual', at: '05/18 08:30' },
    },
    confirmation_label: 'On-time',
    is_favourite: false,
    unread_chat: 0,
    note_description: null,
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'at_plant', text: 'All trucks returned · cycle 3h 12m', time: '08:42' },
      { marker: 'poured', text: 'Final load poured', time: '08:20' },
      { marker: 'info', text: 'Order ticketed at plant', time: '05:18' },
    ],
  },
  {
    order_code: 'ORD-104990',
    order_type: 'PR',
    customer_name: 'Crossland Heavy',
    project_name: 'Yukon Logistics Hub',
    project_code: 'P-619',
    delivery_addr_short: '11500 SW 15th St, Yukon',
    delivery_addr_full: '11500 SW 15th St, Yukon, OK 73099',
    ordered_by_name: 'Brett Allred',
    ordered_by_phone: '(405) 555-0312',
    preferred_communication: 'Phone',
    item_code: '5000P',
    description: '5000 PSI Pump',
    order_qty: 120,
    delivered_qty: 0,
    completion_pct: 0,
    ticket_count: 0,
    total_loads: 15,
    plant_name: 'Yukon',
    plant_code: 'P08',
    zone_name: 'West Metro',
    start_time: '08:00',
    est_finish_time: '13:30',
    status_category: 'PRE_POUR',
    sub_status: 2,
    current_stage_label: 'Weather hold review',
    lifecycle_caption: '⛅ Decision by 06:00',
    lifecycle: [],
    weather: {
      tempF: 64,
      condition: 'Rain 70%',
      windMph: 18,
      rhPct: 82,
      evaporationLevel: 'Low',
      risk: 'risk',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'sms', at: '05/18 17:40' },
      c24: { status: 'pending', channel: null, at: null },
    },
    confirmation_label: '24h pending',
    is_favourite: false,
    unread_chat: 1,
    note_description: 'Weather-dependent — confirm morning of pour',
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'info', text: '48h confirmation — SMS', time: '05/18 17:40' },
      { marker: 'info', text: 'Flagged weather-permitting', time: '05/18 09:12' },
    ],
  },
  {
    order_code: 'ORD-104810',
    order_type: 'CA',
    customer_name: 'Timberland Homes',
    project_name: 'The Reserve Lot 47',
    project_code: 'P-712',
    delivery_addr_short: '5400 N Penn Ave, OKC',
    delivery_addr_full: '5400 N Pennsylvania Ave, Oklahoma City, OK 73112',
    ordered_by_name: 'Sam Pruitt',
    ordered_by_phone: '(405) 555-0420',
    preferred_communication: 'Phone',
    item_code: '3500F',
    description: '3500 Slab',
    order_qty: 22,
    delivered_qty: 0,
    completion_pct: 0,
    ticket_count: 0,
    total_loads: 3,
    plant_name: 'OKC North',
    plant_code: 'P11',
    zone_name: 'OKC Metro',
    start_time: '09:15',
    est_finish_time: '11:45',
    status_category: 'PRE_POUR',
    sub_status: 3,
    current_stage_label: 'On hold',
    lifecycle_caption: '⏸ Awaiting site OK',
    lifecycle: [],
    weather: {
      tempF: 81,
      condition: 'Clear',
      windMph: 9,
      rhPct: 30,
      evaporationLevel: 'Moderate',
      risk: 'none',
    },
    confirmation: {
      c48: { status: 'pending', channel: null, at: null },
      c24: { status: 'pending', channel: null, at: null },
    },
    confirmation_label: 'Held',
    is_favourite: false,
    unread_chat: 0,
    note_description: 'Site not ready — call Mike 30 min out',
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'info', text: 'Foreman placed order on hold', time: '06:55' },
      { marker: 'info', text: 'Order created', time: '05/18 14:02' },
    ],
  },
  {
    order_code: 'ORD-104621',
    order_type: 'PR',
    customer_name: 'ODOT District 4',
    project_name: 'SH-66 Resurface',
    project_code: 'P-298',
    delivery_addr_short: 'SH-66 MM 142, Guthrie OK',
    delivery_addr_full: 'SH-66 Mile Marker 142, Guthrie, OK 73044',
    ordered_by_name: 'Reggie Vance',
    ordered_by_phone: '(405) 555-0501',
    preferred_communication: 'Phone',
    item_code: '4000P',
    description: '4000 PSI Pump',
    order_qty: 60,
    delivered_qty: 21,
    completion_pct: 35,
    ticket_count: 3,
    total_loads: 8,
    plant_name: 'Guthrie',
    plant_code: 'P30',
    zone_name: 'North Metro',
    start_time: '06:00',
    est_finish_time: '12:00',
    status_category: 'IN_PROCESS',
    sub_status: null,
    current_stage_label: 'To Job',
    lifecycle_caption: '▼ To Job 9 CY · 1 tk',
    lifecycle: lc(1, [
      [3, 12, 2],
      [5, 9, 1],
      [2, 0, 0],
      [2, 0, 0],
      [2, 0, 0],
      [2, 0, 0],
      [2, 0, 0],
      [2, 0, 0],
    ]),
    weather: {
      tempF: 90,
      condition: 'Hot · low RH',
      windMph: 22,
      rhPct: 14,
      evaporationLevel: 'Critical',
      risk: 'bad',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'voice', at: '05/17 15:10' },
      c24: { status: 'overdue', channel: null, at: null },
    },
    confirmation_label: '24h overdue',
    is_favourite: true,
    unread_chat: 5,
    note_description: null,
    remove_reason: null,
    exception_label: 'Attention',
    is_critical: true,
    activity: [
      { marker: 'info', text: 'Evap critical — pace risk vs pour', time: '08:05' },
      { marker: 'to_job', text: 'Truck T-3041 rolling to site', time: '07:50' },
      { marker: 'info', text: '24h confirmation missed', time: '06:00' },
    ],
  },
  {
    order_code: 'ORD-105002',
    order_type: 'CA',
    customer_name: 'Allenby Concrete',
    project_name: 'Spec house 19',
    project_code: 'P-845',
    delivery_addr_short: '919 NW 18th St, OKC',
    delivery_addr_full: '919 NW 18th St, Oklahoma City, OK 73106',
    ordered_by_name: 'Pat Allenby',
    ordered_by_phone: '(405) 555-0666',
    preferred_communication: 'Phone',
    item_code: '4000P',
    description: '4000 PSI Pump',
    order_qty: 18,
    delivered_qty: null,
    completion_pct: 0,
    ticket_count: 0,
    total_loads: 4,
    plant_name: 'OKC South',
    plant_code: 'P12',
    zone_name: 'OKC Metro',
    start_time: '10:00',
    est_finish_time: '11:30',
    status_category: 'CANCELED',
    sub_status: null,
    current_stage_label: 'Canceled',
    lifecycle_caption: 'Order removed by customer · see notes',
    lifecycle: [],
    weather: null,
    confirmation: {
      c48: { status: 'not_applicable', channel: null, at: null },
      c24: { status: 'not_applicable', channel: null, at: null },
    },
    confirmation_label: '—',
    is_favourite: false,
    unread_chat: 0,
    note_description: 'Customer reschedule',
    remove_reason: 'Customer reschedule',
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'info', text: 'Order canceled by customer', time: '04:02' },
      { marker: 'info', text: 'Order created', time: '05/18 18:10' },
    ],
  },
  {
    order_code: 'ORD-104888',
    order_type: 'PR',
    customer_name: 'Flintco',
    project_name: 'Moore HS Gym Foundation',
    project_code: 'P-690',
    delivery_addr_short: '300 N Eastern Ave, Moore',
    delivery_addr_full: '300 N Eastern Ave, Moore, OK 73160',
    ordered_by_name: 'Lena Marsh',
    ordered_by_phone: '(405) 555-0744',
    preferred_communication: 'Text',
    item_code: '5000D',
    description: '5000 PSI',
    order_qty: 95,
    delivered_qty: 76,
    completion_pct: 80,
    ticket_count: 8,
    total_loads: 10,
    plant_name: 'Moore',
    plant_code: 'P15',
    zone_name: 'South Metro',
    start_time: '06:45',
    est_finish_time: '10:00',
    status_category: 'IN_PROCESS',
    sub_status: null,
    current_stage_label: 'Washing',
    lifecycle_caption: '▼ Washing 2 trucks',
    lifecycle: lc(5, [
      [5, 0, 0],
      [5, 0, 0],
      [5, 0, 0],
      [5, 0, 0],
      [5, 60, 8],
      [5, 16, 2],
      [3, 0, 0],
      [3, 0, 0],
    ]),
    weather: {
      tempF: 75,
      condition: 'Sunny',
      windMph: 10,
      rhPct: 45,
      evaporationLevel: 'Normal',
      risk: 'none',
    },
    confirmation: {
      c48: { status: 'confirmed', channel: 'voice', at: '05/17 13:00' },
      c24: { status: 'confirmed', channel: 'sms', at: '05/18 13:02' },
    },
    confirmation_label: 'Confirmed',
    is_favourite: false,
    unread_chat: 0,
    note_description: null,
    remove_reason: null,
    exception_label: null,
    is_critical: false,
    activity: [
      { marker: 'washing', text: '2 trucks washing out', time: '09:30' },
      { marker: 'poured', text: 'Load 8 poured', time: '09:05' },
      { marker: 'pouring', text: 'Steady 6 CY/h pour rate', time: '08:10' },
    ],
  },
];

export const SELECTED_ORDER_CODE = 'ORD-104872';

export function getSelectedOrder(): MockOrder {
  return (
    MOCK_ORDERS.find(o => o.order_code === SELECTED_ORDER_CODE) ??
    MOCK_ORDERS[0]
  );
}
